### MULTIPLE LINER REGRESSION MODEL


In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
# to ignore the unwanted future warnings
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv(r"C:\Users\Gaurav\Downloads\telecom_data.csv")
df.head()

Customer_Age  Months_on_Network  Monthly_Charges  Total_Charges  \
0            56                227       118.362654     408.044439   
1            69                115        53.629483    7419.017878   
2            46                 15        45.107272    1152.802890   
3            32                192        30.932769    3217.703927   
4            60                217        62.436365     137.789628   

   Calls_Per_Month  Total_Call_Duration_Minutes  Customer_Service_Calls  \
0              216                  6954.307631                       7   
1              138                  2409.994944                       8   
2               12                  6290.768683                       3   
3              251                  7496.074845                       9   
4              130                  2265.267500                       9   

   International_Plan  Voicemail_Messages  Number_vMail_Messages  \
0                   0                   1                     35   
1                   0                  12                     17   
2                   1                  30                     46   
3                   0                  28                     40   
4                   0                  49                     17   

   Customer_Satisfaction  Account_Length  Number_Of_Lines  Data_Usage_GB  \
0               4.545475             166                3       4.463976   
1               4.351493             128                4      14.154027   
2               4.531127             237                1      15.674766   
3               4.688195             238                1       9.160836   
4               1.418112              35                1      13.991679   

   Churn  Average_Data_Usage_Per_Month  
0      1                      4.463976  
1      1                     14.154027  
2      0                     15.674766  
3      1                      9.160836  
4      0                     13.991679

In [5]:
df.shape

(1000, 16)

In [6]:
df.isnull().sum()

Customer_Age                    0
Months_on_Network               0
Monthly_Charges                 0
Total_Charges                   0
Calls_Per_Month                 0
Total_Call_Duration_Minutes     0
Customer_Service_Calls          0
International_Plan              0
Voicemail_Messages              0
Number_vMail_Messages           0
Customer_Satisfaction           0
Account_Length                  0
Number_Of_Lines                 0
Data_Usage_GB                   0
Churn                           0
Average_Data_Usage_Per_Month    0
dtype: int64

In [7]:
# splitting data x (input) and y (output) features

In [8]:
# input 
X = df.drop(columns = ['Average_Data_Usage_Per_Month'])


In [9]:
X.head()

Customer_Age  Months_on_Network  Monthly_Charges  Total_Charges  \
0            56                227       118.362654     408.044439   
1            69                115        53.629483    7419.017878   
2            46                 15        45.107272    1152.802890   
3            32                192        30.932769    3217.703927   
4            60                217        62.436365     137.789628   

   Calls_Per_Month  Total_Call_Duration_Minutes  Customer_Service_Calls  \
0              216                  6954.307631                       7   
1              138                  2409.994944                       8   
2               12                  6290.768683                       3   
3              251                  7496.074845                       9   
4              130                  2265.267500                       9   

   International_Plan  Voicemail_Messages  Number_vMail_Messages  \
0                   0                   1                     35   
1                   0                  12                     17   
2                   1                  30                     46   
3                   0                  28                     40   
4                   0                  49                     17   

   Customer_Satisfaction  Account_Length  Number_Of_Lines  Data_Usage_GB  \
0               4.545475             166                3       4.463976   
1               4.351493             128                4      14.154027   
2               4.531127             237                1      15.674766   
3               4.688195             238                1       9.160836   
4               1.418112              35                1      13.991679   

   Churn  
0      1  
1      1  
2      0  
3      1  
4      0

In [10]:
X.shape

(1000, 15)

In [11]:
# define the output column 
y = df[['Average_Data_Usage_Per_Month']]

In [12]:
y.head()

Average_Data_Usage_Per_Month
0                      4.463976
1                     14.154027
2                     15.674766
3                      9.160836
4                     13.991679

In [13]:
# now we have to split our data into 80:20 ratio test split 

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.8, random_state = 42)

In [16]:
# shape of the splitted dataset
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(800, 15)
(200, 15)
(800, 1)
(200, 1)


In [17]:
# data normalization ----standard scaler

In [41]:
# import the model
from sklearn.preprocessing import StandardScaler

In [43]:
# object for model 
sc = StandardScaler()

In [45]:
sc.fit(X_train)
X_train_sc= sc.transform(X_train)
X_test_sc= sc.transform(X_test) 

In [47]:
X_train_sc

array([[-0.12149869,  1.58132025,  1.77530268, ..., -1.36855248,
        -0.95471413, -1.03046381],
       [-1.4818759 , -1.32184946,  0.37577161, ...,  1.31050621,
        -0.6934031 , -1.03046381],
       [ 1.4429351 ,  1.39631434, -1.53489549, ..., -1.36855248,
         1.59462606, -1.03046381],
       ...,
       [ 0.49067105, -0.09796419,  0.02290064, ..., -0.47553292,
        -1.51576572,  0.97043679],
       [ 1.30689738,  1.49593291, -0.42795659, ...,  0.41748665,
         1.67794895, -1.03046381],
       [-0.12149869, -0.66721315,  0.82688278, ...,  1.31050621,
        -1.13193072, -1.03046381]])

In [49]:
pd.DataFrame(X_train_sc)

0         1         2         3         4         5         6   \
0   -0.121499  1.581320  1.775303 -0.419794 -1.366539  0.270797 -1.224184   
1   -1.481876 -1.321849  0.375772  1.234237  1.426903 -0.645732  0.487363   
2    1.442935  1.396314 -1.534895 -0.955221 -0.719131  1.154549  1.171982   
3   -1.005744 -1.350312 -1.096825 -1.016846  1.450881  0.572028  0.487363   
4    0.694728  0.770140  1.057531 -0.650568  1.211101 -0.607315  1.171982   
..        ...       ...       ...       ...       ...       ...       ...   
795 -1.753951 -1.393006  1.484231  1.627763  0.515738 -1.310785 -1.566494   
796 -1.345838 -0.581826 -1.217822  1.627679  0.443804  1.002517 -1.566494   
797  0.490671 -0.097964  0.022901  1.666837  1.390936 -0.557913 -0.539565   
798  1.306897  1.495933 -0.427957 -0.793647  0.407837 -0.326906 -1.224184   
799 -0.121499 -0.667213  0.826883  0.608458  1.426903  0.642117  1.514292   

           7         8         9         10        11        12        13  \
0   -0.970437  1.587989  1.061404  1.098159 -0.826371 -1.368552 -0.954714   
1   -0.970437 -1.280659  1.061404 -1.380133 -0.811753  1.310506 -0.693403   
2    1.030464  0.468517  0.503138  0.141499 -1.454957 -1.368552  1.594626   
3    1.030464  0.958286  0.852054 -1.678896  0.343091  1.310506 -1.700112   
4   -0.970437  0.888319 -0.892529  1.511049  0.825494 -0.475533 -0.649279   
..        ...       ...       ...       ...       ...       ...       ...   
795  1.030464  0.048715 -0.683179  0.213153 -1.133355 -0.475533 -0.286667   
796  1.030464  1.238154  0.433354  0.818361 -1.630376  0.417487  0.610506   
797 -0.970437 -1.210692  1.410321  1.433630 -0.080839 -0.475533 -1.515766   
798 -0.970437 -0.720923  1.480104  1.025368  1.264042  0.417487  1.677949   
799 -0.970437 -0.650956  1.410321  1.208892 -1.381866  1.310506 -1.131931   

           14  
0   -1.030464  
1   -1.030464  
2   -1.030464  
3   -1.030464  
4    0.970437  
..        ...  
795  0.970437  
796  0.970437  
797  0.970437  
798 -1.030464  
799 -1.030464  

[800 rows x 15 columns]

### loading the model

In [54]:
from sklearn.linear_model import LinearRegression

In [56]:
# create an object for model 
model1 = LinearRegression()

In [60]:
# fitting or train the data 
model1.fit(X_train_sc, y_train)

LinearRegression()

### now our model has learnt evrtything and ready to prediction

In [62]:
y_pred = model1.predict(X_test_sc)

In [64]:
y_pred

array([[ 3.49415152],
       [19.46224987],
       [11.85273419],
       [ 4.73133181],
       [ 1.23112736],
       [ 8.74869231],
       [13.5760954 ],
       [13.61840164],
       [11.69282136],
       [13.54865155],
       [ 9.79626625],
       [13.71209475],
       [19.95851117],
       [11.48020682],
       [ 4.23421053],
       [17.02094486],
       [ 5.46894155],
       [ 8.76424898],
       [ 2.16117367],
       [ 6.56349842],
       [12.48806578],
       [19.83272529],
       [11.29795971],
       [ 4.61532527],
       [ 7.50768137],
       [ 3.06088685],
       [19.72195577],
       [11.42591725],
       [11.84695153],
       [ 7.85202837],
       [ 6.71986634],
       [14.8022205 ],
       [12.4199526 ],
       [ 8.42709112],
       [ 5.90118687],
       [ 0.20000752],
       [ 8.76655005],
       [ 5.13294493],
       [18.57758929],
       [16.43853575],
       [17.16735417],
       [18.95479696],
       [12.7216278 ],
       [17.89662758],
       [14.3385685 ],
       [ 5

In [66]:
# compare the predict 
y_test

Average_Data_Usage_Per_Month
521                      3.494152
737                     19.462250
740                     11.852734
660                      4.731332
411                      1.231127
..                            ...
408                      5.555310
332                      4.421094
208                      1.869698
613                      8.249418
78                      13.790461

[200 rows x 1 columns]

### CHECKING THE PERFORMANCE OF THE MODEL

In [70]:
from sklearn.metrics import r2_score

In [74]:
#accuracy
print(r2_score(y_test,y_pred))

1.0


### OUR MODEL HAS GIVEN 100% ACCURACY

In [77]:
# checking the value of intercept and cofficient

model1.intercept_

array([10.11159162])

In [79]:
model1.coef_

array([[-1.22463213e-16, -2.97995629e-16,  1.62314149e-15,
         6.24114158e-16, -9.08918393e-16, -3.48697596e-16,
        -8.17100724e-16, -3.07465150e-16,  3.56517418e-16,
        -3.04209370e-16,  3.21516873e-17,  2.63299064e-16,
        -8.35815735e-16,  5.67274783e+00, -1.04334809e-16]])