### simple linear regression model

In [2]:
# import the libraries 
import pandas as pd 
import numpy as np 

In [3]:
df = pd.read_csv(r"C:\Users\Gaurav\Downloads\data.csv")
df.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [4]:
# check the information of sets 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 612.0 bytes


In [5]:
# check the statistical information of dataset
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

### split the dataset into x (input) and y (output)

In [7]:
# input
X = df[['YearsExperience']]


In [8]:
X.head()

YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [9]:
X.shape

(30, 1)

In [10]:
Y=df[['Salary']]

In [11]:
Y.head()

Salary
0   39343
1   46205
2   37731
3   43525
4   39891

### split the data into training and testing phase

In [13]:
# import the train_test_split
from sklearn.model_selection import train_test_split

In [14]:
from sklearn import model_selection

In [15]:
print(dir(model_selection))

['BaseCrossValidator', 'BaseShuffleSplit', 'GridSearchCV', 'GroupKFold', 'GroupShuffleSplit', 'KFold', 'LearningCurveDisplay', 'LeaveOneGroupOut', 'LeaveOneOut', 'LeavePGroupsOut', 'LeavePOut', 'ParameterGrid', 'ParameterSampler', 'PredefinedSplit', 'RandomizedSearchCV', 'RepeatedKFold', 'RepeatedStratifiedKFold', 'ShuffleSplit', 'StratifiedGroupKFold', 'StratifiedKFold', 'StratifiedShuffleSplit', 'TimeSeriesSplit', 'ValidationCurveDisplay', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_plot', '_search', '_split', '_validation', 'check_cv', 'cross_val_predict', 'cross_val_score', 'cross_validate', 'learning_curve', 'permutation_test_score', 'train_test_split', 'typing', 'validation_curve']


In [16]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8, random_state = 42)

In [17]:
print('shape of X_train:', X_train.shape)
print('shape of X_test:', X_test.shape)
print('shape of Y_train:', Y_train.shape)
print('shape of Y_test:', Y_test.shape)

shape of X_train: (24, 1)
shape of X_test: (6, 1)
shape of Y_train: (24, 1)
shape of Y_test: (6, 1)


In [18]:
X_train[:5]

YearsExperience
28             10.3
24              8.7
12              4.0
0               1.1
4               2.2

### building the linear regression model for salary prediction

In [20]:
# import the required algorithm
from sklearn.linear_model import LinearRegression

In [21]:
# now we create the object for Linear Regession
LinearModel = LinearRegression()

In [22]:
# its time to train our model
# for train the model we will be using the "fit()" function

LinearModel.fit(X_train, Y_train)

LinearRegression()

### now our model has learnt every thing , now its time to predict the values

In [24]:
Y_pred = LinearModel.predict(X_test)

In [25]:
Y_pred # prediction salary from our model

array([[115790.21011287],
       [ 71498.27809463],
       [102596.86866063],
       [ 75267.80422384],
       [ 55477.79204548],
       [ 60189.69970699]])

In [26]:
Y_test

Salary
27  112635
15   67938
23  113812
17   83088
8    64445
9    57189

In [53]:
Y_pred[:5]

0
0  115790.210113
1   71498.278095
2  102596.868661
3   75267.804224
4   55477.792045

### check the model performance

In [28]:
from sklearn.metrics import r2_score

In [30]:
print (r2_score(Y_test,Y_pred))

0.9024461774180497


In [32]:
print (r2_score(Y_test,Y_pred)*100)

90.24461774180497


In [34]:
Y_pred = pd.DataFrame(Y_pred)

### check the model with some new data

In [37]:
import warnings
warnings.filterwarnings('ignore')

In [39]:
LinearModel.predict([[ 5.3]])

array([[75267.80422384]])

In [41]:
LinearModel.predict([[ 8.5]])

array([[105424.01325754]])

In [43]:
# check the cofficent value of model
LinearModel.coef_

array([[9423.81532303]])

In [45]:
LinearModel.intercept_

array([25321.58301178])